### ISSUE TITLE
"Unexpected flag -s."

### ISSUE THREAD

**Issue by Xanderplayz17** [TheRealMichaelWang/superforth#26]
So I was trying to compile a script in superforth but it just gave a output of 
C:\Users\Administrator\Desktop\Superforth>sf -r examples/conways.txt
Unexpected flag -s. .

C:\Users\Administrator\Desktop\Superforth>

**Comment by TheRealMichaelWang** [comment]
* You are supposed to specify a source flag after each operation flag, though I may change it in the future if a lot of people see it as unintuitive.
* Also, because conways.txt is a source file, it cannot be ran directly as a binary. 

Assuming you've renamed the SuperForth executable to sf, the correct command line input would be:
```
sf -cr -s "examples/conways.txt"
```
