### ISSUE TITLE
Syntax error in conways.txt example script

### ISSUE THREAD

**Issue by Xanderplayz16** [TheRealMichaelWang/superforth#32]
Here is what happened.
![Screenshot 2022-05-01 205027](https://user-images.githubusercontent.com/74632800/166172183-9d4ba07b-d796-4e3b-98d0-3a91bf9cd0b1.png)

**Comment by Xanderplayz16** [comment]
The file may be corrupted, I had problems similar to that when compiling NTVDM (I got a Access Violation error which means in some cases the file is corrupted.) .

**Comment by Xanderplayz16** [comment]
I just tried fizzbuzz and it gave the same error (other than the location of the error which was different)

**Comment by TheRealMichaelWang** [comment]
Sorry for the mistake, the stdlib folder is missing random.txt, ([which can be found here](https://github.com/TheRealMichaelWang/superforth/blob/main/examples/random.txt)).

Just keep in mind that, you are only supposed to use `-r` with SuperForth binary files. In this case, please use `-cr` which *compiles* and runs the source file.

**The Fix:** Copy the items [in the standard library folder](https://github.com/TheRealMichaelWang/superforth/tree/main/stdlib) into SuperForth's working directory, including ["random.txt"](https://github.com/TheRealMichaelWang/superforth/blob/main/examples/random.txt) and any other file the program requires (most of which can probably be found in [the examples folder](https://github.com/TheRealMichaelWang/superforth/tree/main/examples)). 

The current error occurred at row 1, col 32 and its because it "cant open a file". If you look at row1, the code is 
```
include "random.txt";
```
That means that it can open the source file, and has begun compilation but it cannot find `random.txt`.

**Comment by TheRealMichaelWang** [comment]
In the future, improved error reporting will *definitely* be something that'll be worked on.
